// Country list with ISO dial codes. Used for the nationality dropdown
// and the WhatsApp number prefix on the public booking form.

export type Country = { name: string; dial: string };

export const COUNTRIES: Country[] = [
  { name: "Malaysia", dial: "+60" },
  { name: "Singapore", dial: "+65" },
  { name: "Indonesia", dial: "+62" },
  { name: "Thailand", dial: "+66" },
  { name: "Philippines", dial: "+63" },
  { name: "Vietnam", dial: "+84" },
  { name: "China", dial: "+86" },
  { name: "Hong Kong", dial: "+852" },
  { name: "Taiwan", dial: "+886" },
  { name: "Japan", dial: "+81" },
  { name: "South Korea", dial: "+82" },
  { name: "India", dial: "+91" },
  { name: "Bangladesh", dial: "+880" },
  { name: "Pakistan", dial: "+92" },
  { name: "Sri Lanka", dial: "+94" },
  { name: "Nepal", dial: "+977" },
  { name: "Myanmar", dial: "+95" },
  { name: "Cambodia", dial: "+855" },
  { name: "Laos", dial: "+856" },
  { name: "Brunei", dial: "+673" },
  { name: "Australia", dial: "+61" },
  { name: "New Zealand", dial: "+64" },
  { name: "United Kingdom", dial: "+44" },
  { name: "United States", dial: "+1" },
  { name: "Canada", dial: "+1" },
  { name: "Ireland", dial: "+353" },
  { name: "Germany", dial: "+49" },
  { name: "France", dial: "+33" },
  { name: "Italy", dial: "+39" },
  { name: "Spain", dial: "+34" },
  { name: "Portugal", dial: "+351" },
  { name: "Netherlands", dial: "+31" },
  { name: "Belgium", dial: "+32" },
  { name: "Switzerland", dial: "+41" },
  { name: "Austria", dial: "+43" },
  { name: "Sweden", dial: "+46" },
  { name: "Norway", dial: "+47" },
  { name: "Denmark", dial: "+45" },
  { name: "Finland", dial: "+358" },
  { name: "Iceland", dial: "+354" },
  { name: "Poland", dial: "+48" },
  { name: "Czech Republic", dial: "+420" },
  { name: "Hungary", dial: "+36" },
  { name: "Romania", dial: "+40" },
  { name: "Greece", dial: "+30" },
  { name: "Turkey", dial: "+90" },
  { name: "Russia", dial: "+7" },
  { name: "Ukraine", dial: "+380" },
  { name: "Saudi Arabia", dial: "+966" },
  { name: "United Arab Emirates", dial: "+971" },
  { name: "Qatar", dial: "+974" },
  { name: "Kuwait", dial: "+965" },
  { name: "Bahrain", dial: "+973" },
  { name: "Oman", dial: "+968" },
  { name: "Jordan", dial: "+962" },
  { name: "Lebanon", dial: "+961" },
  { name: "Israel", dial: "+972" },
  { name: "Egypt", dial: "+20" },
  { name: "South Africa", dial: "+27" },
  { name: "Nigeria", dial: "+234" },
  { name: "Kenya", dial: "+254" },
  { name: "Ghana", dial: "+233" },
  { name: "Ethiopia", dial: "+251" },
  { name: "Morocco", dial: "+212" },
  { name: "Tunisia", dial: "+216" },
  { name: "Algeria", dial: "+213" },
  { name: "Brazil", dial: "+55" },
  { name: "Argentina", dial: "+54" },
  { name: "Mexico", dial: "+52" },
  { name: "Chile", dial: "+56" },
  { name: "Colombia", dial: "+57" },
  { name: "Peru", dial: "+51" },
  { name: "Venezuela", dial: "+58" },
  { name: "Uruguay", dial: "+598" },
  { name: "Ecuador", dial: "+593" },
  { name: "Bolivia", dial: "+591" },
  { name: "Paraguay", dial: "+595" },
  { name: "Costa Rica", dial: "+506" },
  { name: "Panama", dial: "+507" },
  { name: "Dominican Republic", dial: "+1" },
  { name: "Cuba", dial: "+53" },
  { name: "Jamaica", dial: "+1" },
  { name: "Trinidad and Tobago", dial: "+1" },
  { name: "Mongolia", dial: "+976" },
  { name: "Maldives", dial: "+960" },
  { name: "Bhutan", dial: "+975" },
  { name: "Afghanistan", dial: "+93" },
  { name: "Iran", dial: "+98" },
  { name: "Iraq", dial: "+964" },
  { name: "Syria", dial: "+963" },
  { name: "Yemen", dial: "+967" },
  { name: "Kazakhstan", dial: "+7" },
  { name: "Uzbekistan", dial: "+998" },
  { name: "Azerbaijan", dial: "+994" },
  { name: "Georgia", dial: "+995" },
  { name: "Armenia", dial: "+374" },
  { name: "Belarus", dial: "+375" },
  { name: "Bulgaria", dial: "+359" },
  { name: "Croatia", dial: "+385" },
  { name: "Serbia", dial: "+381" },
  { name: "Slovakia", dial: "+421" },
  { name: "Slovenia", dial: "+386" },
  { name: "Lithuania", dial: "+370" },
  { name: "Latvia", dial: "+371" },
  { name: "Estonia", dial: "+372" },
  { name: "Cyprus", dial: "+357" },
  { name: "Malta", dial: "+356" },
  { name: "Luxembourg", dial: "+352" },
  { name: "Monaco", dial: "+377" },
  { name: "Other", dial: "" },
];

export function dialCodeFor(name: string): string {
  return COUNTRIES.find((c) => c.name === name)?.dial || "";
}
